### PR TITLE
Apply url_encode to mailto: subject & body params

### PR DESCRIPTION
**Pull request by erkde**
I'm guessing this is used by various apps, beyond the WCAG docs where I've noticed it..

But, over in those docs, the `mailto` link in the footer box has a kind of strange mix of escaping, for example on [this page](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/)

```html
<a href="mailto:wai-eo-editors@w3.org?subject=[en]%20What%E2%80%99s%20New%20in%20WCAG%202.1&amp;body=[put%20comment%20here...]" class="button"><span>E-mail</span></a>
```

[MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#specifying_details) suggests [URL (percent) encoding](https://shopify.github.io/liquid/filters/url_encode/) the value of each field, producing something like:

```html
<a href="mailto:wai-eo-editors@w3.org?subject=%5Ben%5D%20What%E2%80%99s%20New%20in%20WCAG%202.1&amp;body=%5Bput%20comment%20here...%5D%0D%0A" class="button"><span>E-mail</span></a>
```

Note; I'm not sure how the `&` character just before `body` is being translated to `&amp;`, but I think this change will at least encode the `[ ]` characters to percent values.

### CODE REVIEW

**Comment by erkde** [comment]
Hmm, it's encoded the `[ ]` characters, but now each space is a `+` char, which wasn't the intent.

**Comment by ADTC** [comment]
Try applying an additional filter: `| replace: "+", "%20"`

But this will only work if any existing `+` characters are converted to `%2b`, and _**then**_ the spaces are converted to `+`, so be sure to test that.

**Comment by erkde** [comment]
> Try applying an additional filter: `| replace: "+", "%20"`
> 
> But this will only work if any existing `+` characters are converted to `%2b`, and _**then**_ the spaces are converted to `+`, so be sure to test that.

I agree with you in Shopify/liquid/issues/1412 - it would be really nice to have this as an option in `url_encode`, but anyway - it's encoding correctly and seems to do the trick:

```html
<a href="mailto:wai-eo-editors@w3.org?subject=%5Ben%5D%20WAI%20Website%20Manual&amp;body=%5Bput%20comment%20here...%5D" class="button"><span>E-mail</span></a>
```

Screen Shot 2021-03-11 at 9 18 41 am

**Comment by remibetin** [comment]
Thank you! This was resolved by https://github.com/w3c/wai-website-theme/pull/83

**Pull request closed without merging**
