### PR TITLE
Allow for inclusion of one or more resources in h1 and document this

### PR DESCRIPTION
**Pull request by hidde**
@slhenry @nitedog I have implemented the changes as discussed in https://github.com/w3c/wai-curricula/issues/215#issuecomment-773401261. 

This PR adds:

* logic that honours the `parent_in_h1` property
* CSS that deals with including “in … ” inside the `h1` in addition to underneath the `h1`
* documentation for how to use the `parent_in_h1` and `resource.ref` properties

Some things you can look at in this PR: 

- [Preview of the documentation of this behavior](https://deploy-preview-26--wai-website-theme.netlify.app/components/headings/) on the Headings page of the WAI Design Components
- [The `if` statements added](https://github.com/w3c/wai-website-theme/pull/26/files#diff-907a69846a1f6b238f1c43199984197d12c7eab26f3c3adcd45d628b26644950) 

As mentioned before, we are adding a lot of complexity in order to get this level of flexibility, I'd like to repeat my previous warning that this may prove difficult to understand when we look at it in the future, both in documentation and code.

Feel free to try out the behavior too, you could add the behavior to any of the pages  in the WAI website theme.

### CODE REVIEW

**Comment by nitedog** [comment]
adding @daniel-montalvo as reviewer and test bunny :-)

**Review by daniel-montalvo — APPROVED** [review]
Thanks. Looks good to me!

**Comment by hidde** [comment]
@slhenry Are you okay with me merging these changes?

**Review by nitedog — APPROVED** [review]
Can't judge the code but the output in the documentation matches what we agreed on.

**Comment by slhenry** [comment]
Thanks, Hidde. I'll try to make some time to suggest edits to the documentation. Also, once it's implemented in the curricula, we might want to provide a link to that and a live example?

I'll add it to the Perspectives Videos as another test. :-)

**Review by slhenry — APPROVED** [review]

**Comment by daniel-montalvo** [comment]
> [...] Also, once it's implemented in the curricula, we might want to provide a link to that as a live example?

This is already added to the front-matter in the curricula repo. For example in

https://raw.githubusercontent.com/w3c/wai-curricula/master/content/foundation/what-is-web-accessibility.md

And this would produce

# What is Web Accessibility in [Foundation Modules](https://wai-curricula.netlify.app/curricula/foundation-modules/what-is-web-accessibility), [Curricula](https://wai-curricula.netlify.app/curricula/foundation-modules/)

[+ appropriate WAI styles]

I am assuming we need to wait till these changes are merged for them to be displayed in the curricula previews.

**Comment by slhenry** [comment]
@hidde Please let Daniel and me know when merged. You can see his previews as a test, and I'll let you know when I've added to the Perspectives Videos ```name: "@@"```

**Comment by hidde** [comment]
Cool, in that case I'll merge now. 

I believe previews across our subsites will use the latest wai-website-theme, which, only when this PR is merged, will contain this PR's changes. I'll try and retrigger the build for @daniel-montalvo's branch so that we can see if it works!

**Pull request merged**
